ファイルの作成方法について追記
Mets-org/www.mets-svr.com pull request #6
Opened 2023-04-04 07:23 UTC by Crab55e

2023-04-06 13:46 UTC, ikafly144 requested changes
カニ鍋しようか

2023-04-06 13:46 UTC, ikafly144 commented on CREATE_NEW_BLOG_POST.md
> +- 「美味しいスルメの作り方についての記事を作ったので、mets 鯖のブログに入れてほしい、プルリクを送ろう」
ん？

2023-04-06 15:40 UTC, Crab55e commented on CREATE_NEW_BLOG_POST.md
> +- 「美味しいスルメの作り方についての記事を作ったので、mets 鯖のブログに入れてほしい、プルリクを送ろう」
；；

2023-04-19 11:17 UTC, ikafly144 approved these changes
チャーシュー食おう

2023-04-19 11:17 UTC, merged